import { ENCLOSURES } from "./enclosures"
import type { Dimensions, EnclosureId, PedalSpec, PowerSpec } from "./types"

/**
 * The pedal spec catalogue.
 *
 * Two populations, chosen deliberately.
 *
 * FIRST, everything in `lib/rigs/data.ts`. A documented artist rig that loads
 * onto the board as grey rectangles of guessed size is worse than not offering
 * it, so every pedal named in those 23 rigs has an entry here. That includes
 * the tape echoes and rack units, which are marked `offBoard`: a Binson
 * Echorec is genuinely part of Gilmour's rig and genuinely does not sit on a
 * Pedaltrain, and saying so is more useful than either omitting it or
 * reporting that it does not fit.
 *
 * SECOND, the pedals people are actually buying now. This is a planner, and
 * most people plan the board they are about to build rather than one from
 * 1973.
 *
 * WHAT THIS LIST IS NOT: a recommendation. It is ordered by brand and model,
 * never by anything to do with what a merchant pays us, and inclusion means
 * "players put this on boards", not "buy this". The site's footer promises
 * commission never affects what a shopper sees, and a hand-curated gear list
 * on the most opinion-shaped page here is exactly where that promise would be
 * easiest to quietly break.
 *
 * ON THE NUMBERS. Dimensions marked `enclosure` come from the standard box the
 * pedal is built in and are right to a millimetre or two of powder coat.
 * Dimensions marked `maker` come from a published spec. Power figures marked
 * `estimate` are typical draws for the kind of circuit and nothing more: they
 * are enough to size a supply and are not a guarantee, which is chain.ts's
 * second rule and is enforced by the power planner refusing to certify a board
 * whose figures are estimates. Before you drill a board or trust a supply,
 * check the maker's own spec. The UI says so too.
 */

/** Build a dimensions record from a standard enclosure. */
function box(id: EnclosureId): Dimensions {
  return { ...ENCLOSURES[id].dims }
}

/** 9V DC, center negative, the near-universal case. */
function dc(ma: number, source: PowerSpec["source"] = "estimate"): PowerSpec {
  return { ma, volts: 9, polarity: "center-negative", dcJack: true, source }
}

/** Vintage fuzz and boosters with no DC input at all. */
function batteryOnly(note = "No DC jack. Battery only unless modified."): PowerSpec {
  return { ma: 0, volts: 9, polarity: "center-negative", dcJack: false, source: "maker", note }
}

export const PEDALS: PedalSpec[] = [
  /* ---------------------------------------------------------------- Boss -- */
  {
    id: "boss-bd-2",
    brand: "Boss",
    model: "BD-2 Blues Driver",
    type: "drive",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(20, "maker"),
    weightG: 450,
  },
  {
    id: "boss-ds-1",
    brand: "Boss",
    model: "DS-1 Distortion",
    type: "drive",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(6, "maker"),
    weightG: 450,
  },
  {
    id: "boss-ds-2",
    brand: "Boss",
    model: "DS-2 Turbo Distortion",
    type: "drive",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(25, "maker"),
    weightG: 450,
  },
  {
    id: "boss-sd-1",
    brand: "Boss",
    model: "SD-1 Super Overdrive",
    type: "drive",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(10, "maker"),
    weightG: 450,
  },
  {
    id: "boss-mt-2",
    brand: "Boss",
    model: "MT-2 Metal Zone",
    type: "drive",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(20, "maker"),
    weightG: 450,
  },
  {
    id: "boss-hm-2",
    brand: "Boss",
    model: "HM-2 Heavy Metal",
    type: "drive",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(20),
    weightG: 450,
  },
  {
    id: "boss-tu-3",
    brand: "Boss",
    model: "TU-3 Chromatic Tuner",
    type: "tuner",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(85, "maker"),
    weightG: 450,
    note: undefined,
  } as PedalSpec,
  {
    id: "boss-tu-2",
    brand: "Boss",
    model: "TU-2 Chromatic Tuner",
    type: "tuner",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(55, "maker"),
    weightG: 450,
  },
  {
    id: "boss-ce-2",
    brand: "Boss",
    model: "CE-2 Chorus",
    type: "modulation",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(20),
    weightG: 450,
  },
  {
    id: "boss-ce-1",
    brand: "Boss",
    model: "CE-1 Chorus Ensemble",
    type: "modulation",
    dims: { widthMm: 190, depthMm: 210, heightMm: 75, source: "estimate" },
    power: { ma: 0, volts: 117, polarity: "center-negative", dcJack: false, source: "maker", note: "Mains powered, not a 9V pedal. It is a floor unit rather than a board pedal." },
    weightG: 2800,
  },
  {
    id: "boss-ch-1",
    brand: "Boss",
    model: "CH-1 Super Chorus",
    type: "modulation",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(25, "maker"),
    weightG: 450,
  },
  {
    id: "boss-bf-2",
    brand: "Boss",
    model: "BF-2 Flanger",
    type: "modulation",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(20),
    weightG: 450,
  },
  {
    id: "boss-dd-3",
    brand: "Boss",
    model: "DD-3 Digital Delay",
    type: "delay",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(55, "maker"),
    weightG: 450,
  },
  {
    id: "boss-dd-2",
    brand: "Boss",
    model: "DD-2 Digital Delay",
    type: "delay",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(55),
    weightG: 450,
  },
  {
    id: "boss-dd-8",
    brand: "Boss",
    model: "DD-8 Digital Delay",
    type: "delay",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(75, "maker"),
    weightG: 450,
  },
  {
    id: "boss-rv-6",
    brand: "Boss",
    model: "RV-6 Reverb",
    type: "reverb",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(65, "maker"),
    weightG: 450,
  },
  {
    id: "boss-ge-7",
    brand: "Boss",
    model: "GE-7 Equalizer",
    type: "eq",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(25, "maker"),
    weightG: 450,
  },
  {
    id: "boss-oc-3",
    brand: "Boss",
    model: "OC-3 Super Octave",
    type: "pitch",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(40, "maker"),
    weightG: 450,
  },
  {
    id: "boss-tr-2",
    brand: "Boss",
    model: "TR-2 Tremolo",
    type: "modulation",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(15, "maker"),
    weightG: 450,
  },
  {
    id: "boss-ph-3",
    brand: "Boss",
    model: "PH-3 Phase Shifter",
    type: "modulation",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(40, "maker"),
    weightG: 450,
  },
  {
    id: "boss-cs-3",
    brand: "Boss",
    model: "CS-3 Compression Sustainer",
    type: "compressor",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(15, "maker"),
    weightG: 450,
  },
  {
    id: "boss-rc-5",
    brand: "Boss",
    model: "RC-5 Loop Station",
    type: "looper",
    enclosure: "boss-compact",
    dims: box("boss-compact"),
    power: dc(170, "maker"),
    weightG: 450,
  },
  {
    id: "boss-dd-200",
    brand: "Boss",
    model: "DD-200 Digital Delay",
    type: "delay",
    enclosure: "boss-200",
    dims: box("boss-200"),
    power: dc(300, "maker"),
    weightG: 570,
  },
  {
    id: "boss-rv-200",
    brand: "Boss",
    model: "RV-200 Reverb",
    type: "reverb",
    enclosure: "boss-200",
    dims: box("boss-200"),
    power: dc(300, "maker"),
    weightG: 570,
  },
  {
    id: "boss-dd-500",
    brand: "Boss",
    model: "DD-500 Digital Delay",
    type: "delay",
    enclosure: "boss-500",
    dims: box("boss-500"),
    power: dc(300, "maker"),
    weightG: 1200,
  },
  {
    id: "boss-rv-500",
    brand: "Boss",
    model: "RV-500 Reverb",
    type: "reverb",
    enclosure: "boss-500",
    dims: box("boss-500"),
    power: dc(300, "maker"),
    weightG: 1200,
  },

  /* ----------------------------------------------------------------- MXR -- */
  {
    id: "mxr-phase-90",
    brand: "MXR",
    model: "Phase 90",
    type: "modulation",
    enclosure: "mxr-compact",
    dims: box("mxr-compact"),
    power: dc(3, "maker"),
    weightG: 400,
  },
  {
    id: "mxr-dyna-comp",
    brand: "MXR",
    model: "Dyna Comp",
    type: "compressor",
    enclosure: "mxr-compact",
    dims: box("mxr-compact"),
    power: dc(4, "maker"),
    weightG: 400,
  },
  {
    id: "mxr-distortion-plus",
    brand: "MXR",
    model: "Distortion+",
    type: "drive",
    enclosure: "mxr-compact",
    dims: box("mxr-compact"),
    power: dc(3),
    weightG: 400,
    aliases: ["Distortion Plus"],
  },
  {
    id: "mxr-micro-amp",
    brand: "MXR",
    model: "Micro Amp",
    type: "drive",
    enclosure: "mxr-compact",
    dims: box("mxr-compact"),
    power: dc(2, "maker"),
    weightG: 400,
  },
  {
    id: "mxr-carbon-copy",
    brand: "MXR",
    model: "Carbon Copy Analog Delay",
    type: "delay",
    enclosure: "mxr-compact",
    dims: box("mxr-compact"),
    power: dc(26, "maker"),
    weightG: 400,
  },
  {
    id: "mxr-flanger",
    brand: "MXR",
    model: "Flanger",
    type: "modulation",
    dims: { widthMm: 121, depthMm: 145, heightMm: 60, source: "enclosure" },
    power: dc(35),
    weightG: 900,
  },
  {
    id: "mxr-stereo-chorus",
    brand: "MXR",
    model: "Stereo Chorus",
    type: "modulation",
    dims: { widthMm: 121, depthMm: 145, heightMm: 60, source: "enclosure" },
    power: dc(50),
    weightG: 800,
    aliases: ["M134 Stereo Chorus"],
  },
  {
    id: "mxr-10-band-eq",
    brand: "MXR",
    model: "10-Band EQ",
    type: "eq",
    dims: { widthMm: 121, depthMm: 145, heightMm: 60, source: "enclosure" },
    power: dc(30, "maker"),
    weightG: 900,
    aliases: ["M108 10 Band EQ", "Ten Band EQ"],
  },
  {
    id: "mxr-phase-95",
    brand: "MXR",
    model: "Phase 95",
    type: "modulation",
    enclosure: "mxr-mini",
    dims: box("mxr-mini"),
    power: dc(3, "maker"),
    weightG: 230,
  },

  /* ---------------------------------------------------- Electro-Harmonix -- */
  {
    id: "ehx-big-muff-pi",
    brand: "Electro-Harmonix",
    model: "Big Muff Pi",
    type: "drive",
    enclosure: "ehx-large",
    dims: box("ehx-large"),
    power: dc(3, "maker"),
    weightG: 900,
    aliases: ["Big Muff", "Op-Amp Big Muff"],
  },
  {
    id: "ehx-nano-big-muff",
    brand: "Electro-Harmonix",
    model: "Nano Big Muff Pi",
    type: "drive",
    enclosure: "ehx-nano",
    dims: box("ehx-nano"),
    power: dc(3, "maker"),
    weightG: 340,
  },
  {
    id: "ehx-soul-food",
    brand: "Electro-Harmonix",
    model: "Soul Food",
    type: "drive",
    enclosure: "ehx-nano",
    dims: box("ehx-nano"),
    power: dc(8, "maker"),
    weightG: 340,
  },
  {
    id: "ehx-small-stone",
    brand: "Electro-Harmonix",
    model: "Small Stone",
    type: "modulation",
    enclosure: "ehx-xo",
    dims: box("ehx-xo"),
    power: dc(20),
    weightG: 450,
  },
  {
    id: "ehx-small-clone",
    brand: "Electro-Harmonix",
    model: "Small Clone",
    type: "modulation",
    enclosure: "ehx-nano",
    dims: box("ehx-nano"),
    power: dc(25),
    weightG: 340,
  },
  {
    id: "ehx-electric-mistress",
    brand: "Electro-Harmonix",
    model: "Electric Mistress",
    type: "modulation",
    enclosure: "ehx-large",
    dims: box("ehx-large"),
    power: dc(25),
    weightG: 900,
  },
  {
    id: "ehx-deluxe-memory-man",
    brand: "Electro-Harmonix",
    model: "Deluxe Memory Man",
    type: "delay",
    dims: { widthMm: 152, depthMm: 184, heightMm: 64, source: "estimate" },
    power: { ma: 100, volts: 24, polarity: "center-negative", dcJack: true, source: "maker", note: "24V, not 9V. It ships with its own adapter and most boards' supplies cannot feed it." },
    weightG: 1400,
    aliases: ["DMM"],
  },
  {
    id: "ehx-micro-pog",
    brand: "Electro-Harmonix",
    model: "Micro POG",
    type: "pitch",
    enclosure: "ehx-xo",
    dims: box("ehx-xo"),
    power: dc(150, "maker"),
    weightG: 500,
  },
  {
    id: "ehx-pog2",
    brand: "Electro-Harmonix",
    model: "POG2",
    type: "pitch",
    enclosure: "ehx-large",
    dims: box("ehx-large"),
    power: dc(200, "maker"),
    weightG: 950,
  },
  {
    id: "ehx-micro-synth",
    brand: "Electro-Harmonix",
    model: "Micro Synth",
    type: "filter",
    enclosure: "ehx-large",
    dims: box("ehx-large"),
    power: dc(100),
    weightG: 950,
  },
  {
    id: "ehx-holy-grail",
    brand: "Electro-Harmonix",
    model: "Holy Grail",
    type: "reverb",
    enclosure: "ehx-xo",
    dims: box("ehx-xo"),
    power: dc(100),
    weightG: 450,
  },

  /* -------------------------------------------------------------- Ibanez -- */
  {
    id: "ibanez-ts9",
    brand: "Ibanez",
    model: "TS9 Tube Screamer",
    type: "drive",
    dims: { widthMm: 74, depthMm: 124, heightMm: 53, source: "maker" },
    power: dc(8, "maker"),
    weightG: 500,
  },
  {
    id: "ibanez-ts808",
    brand: "Ibanez",
    model: "TS808 Tube Screamer",
    type: "drive",
    dims: { widthMm: 74, depthMm: 124, heightMm: 53, source: "maker" },
    power: dc(8, "maker"),
    weightG: 500,
  },
  {
    id: "ibanez-ts-mini",
    brand: "Ibanez",
    model: "Tube Screamer Mini",
    type: "drive",
    enclosure: "mxr-mini",
    dims: box("mxr-mini"),
    power: dc(8, "maker"),
    weightG: 230,
  },
  {
    id: "ibanez-wh10",
    brand: "Ibanez",
    model: "WH10 Wah",
    type: "filter",
    enclosure: "wah-treadle",
    dims: box("wah-treadle"),
    power: dc(20),
    weightG: 900,
    treadle: true,
  },
  {
    id: "ibanez-dfl",
    brand: "Ibanez",
    model: "DFL Flanger",
    type: "modulation",
    dims: { widthMm: 74, depthMm: 124, heightMm: 53, source: "estimate" },
    power: dc(25),
    weightG: 500,
  },

  /* -------------------------------------------------- Dunlop / Vox / wahs -- */
  {
    id: "dunlop-cry-baby",
    brand: "Dunlop",
    model: "Cry Baby GCB95",
    type: "filter",
    enclosure: "wah-treadle",
    dims: box("wah-treadle"),
    power: dc(3, "maker"),
    weightG: 1500,
    treadle: true,
    aliases: ["Cry Baby"],
  },
  {
    id: "vox-v846",
    brand: "Vox",
    model: "V846 Wah",
    type: "filter",
    enclosure: "wah-treadle",
    dims: box("wah-treadle"),
    power: batteryOnly("Original V846 is battery only."),
    weightG: 1500,
    treadle: true,
  },
  {
    id: "vox-v847",
    brand: "Vox",
    model: "V847 Wah",
    type: "filter",
    enclosure: "wah-treadle",
    dims: box("wah-treadle"),
    power: dc(3),
    weightG: 1400,
    treadle: true,
  },
  {
    id: "dunlop-volume-x-mini",
    brand: "Dunlop",
    model: "Volume (X) Mini",
    type: "volume",
    dims: { widthMm: 70, depthMm: 172, heightMm: 65, source: "maker" },
    power: { ma: 0, volts: 9, polarity: "center-negative", dcJack: false, source: "maker", note: "Passive. No power needed." },
    weightG: 700,
    treadle: true,
  },
  {
    id: "ernie-ball-vp-jr",
    brand: "Ernie Ball",
    model: "VP Jr 250K",
    type: "volume",
    enclosure: "volume-treadle",
    dims: box("volume-treadle"),
    power: { ma: 0, volts: 9, polarity: "center-negative", dcJack: false, source: "maker", note: "Passive. No power needed." },
    weightG: 1400,
    treadle: true,
  },

  /* ------------------------------------------------------------ Vintage -- */
  {
    id: "dallas-arbiter-fuzz-face",
    brand: "Dallas Arbiter",
    model: "Fuzz Face",
    type: "drive",
    dims: { widthMm: 114, depthMm: 114, heightMm: 60, source: "estimate" },
    power: batteryOnly("Round enclosure, battery only. Reissues vary and many are positive ground, which means an isolated output is mandatory."),
    weightG: 700,
    aliases: ["Fuzz Face"],
  },
  {
    id: "dallas-rangemaster",
    brand: "Dallas",
    model: "Rangemaster Treble Booster",
    type: "drive",
    dims: { widthMm: 108, depthMm: 76, heightMm: 51, source: "estimate" },
    power: batteryOnly("Positive ground germanium. Battery only in original form."),
    weightG: 350,
    aliases: ["Rangemaster"],
  },
  {
    id: "proco-rat",
    brand: "ProCo",
    model: "RAT 2",
    type: "drive",
    dims: { widthMm: 89, depthMm: 114, heightMm: 50, source: "maker" },
    power: dc(6, "maker"),
    weightG: 700,
    aliases: ["Rat"],
  },
  {
    id: "roger-mayer-octavia",
    brand: "Roger Mayer",
    model: "Octavia",
    type: "pitch",
    dims: { widthMm: 95, depthMm: 145, heightMm: 55, source: "estimate" },
    power: dc(10),
    weightG: 600,
  },
  {
    id: "tycobrahe-octavia",
    brand: "Tycobrahe",
    model: "Octavia",
    type: "pitch",
    dims: { widthMm: 121, depthMm: 145, heightMm: 60, source: "estimate" },
    power: batteryOnly(),
    weightG: 800,
  },
  {
    id: "univox-uni-vibe",
    brand: "Univox",
    model: "Uni-Vibe",
    type: "modulation",
    dims: { widthMm: 235, depthMm: 190, heightMm: 95, source: "estimate" },
    power: { ma: 0, volts: 120, polarity: "center-negative", dcJack: false, source: "maker", note: "Mains powered, with a separate expression treadle. A floor unit, not a board pedal." },
    weightG: 3000,
  },
  {
    id: "fulltone-deja-vibe",
    brand: "Fulltone",
    model: "Deja Vibe",
    type: "modulation",
    dims: { widthMm: 121, depthMm: 178, heightMm: 65, source: "estimate" },
    power: dc(100),
    weightG: 1300,
  },
  {
    id: "ross-compressor",
    brand: "Ross",
    model: "Compressor",
    type: "compressor",
    dims: { widthMm: 95, depthMm: 121, heightMm: 55, source: "estimate" },
    power: dc(5),
    weightG: 500,
  },
  {
    id: "foxx-foot-phaser",
    brand: "Foxx",
    model: "Foot Phaser",
    type: "modulation",
    dims: { widthMm: 102, depthMm: 152, heightMm: 60, source: "estimate" },
    power: batteryOnly(),
    weightG: 700,
  },
  {
    id: "fender-blender",
    brand: "Fender",
    model: "Blender",
    type: "drive",
    dims: { widthMm: 121, depthMm: 165, heightMm: 60, source: "estimate" },
    power: batteryOnly(),
    weightG: 900,
  },
  {
    id: "maestro-parametric-filter",
    brand: "Maestro",
    model: "Parametric Filter",
    type: "filter",
    dims: { widthMm: 152, depthMm: 190, heightMm: 65, source: "estimate" },
    power: batteryOnly(),
    weightG: 1100,
  },
  {
    id: "marshall-shredmaster",
    brand: "Marshall",
    model: "ShredMaster",
    type: "drive",
    dims: { widthMm: 121, depthMm: 145, heightMm: 55, source: "estimate" },
    power: dc(10),
    weightG: 700,
  },
  {
    id: "demeter-tremulator",
    brand: "Demeter",
    model: "Tremulator",
    type: "modulation",
    enclosure: "1590B",
    dims: box("1590B"),
    power: dc(10),
    weightG: 400,
  },
  {
    id: "zvex-fuzz-factory",
    brand: "Z.Vex",
    model: "Fuzz Factory",
    type: "drive",
    dims: { widthMm: 102, depthMm: 64, heightMm: 51, source: "maker" },
    power: dc(1, "maker"),
    weightG: 300,
  },
  {
    id: "heil-talk-box",
    brand: "Heil Sound",
    model: "Talk Box",
    type: "utility",
    dims: { widthMm: 165, depthMm: 121, heightMm: 65, source: "estimate" },
    power: { ma: 0, volts: 9, polarity: "center-negative", dcJack: false, source: "maker", note: "Passive: it sits between amp head and speaker, with a tube to the mic. Not a line-level board pedal." },
    weightG: 1200,
  },

  /* ----------------------------------------------------- DigiTech / Line 6 -- */
  {
    id: "digitech-whammy",
    brand: "DigiTech",
    model: "Whammy",
    type: "pitch",
    dims: { widthMm: 133, depthMm: 197, heightMm: 64, source: "maker" },
    power: { ma: 300, volts: 9, polarity: "center-negative", dcJack: true, source: "maker", note: "Ships with its own high-current adapter. Check the revision: some Whammy generations want more than a typical 100mA output supplies." },
    weightG: 1400,
    treadle: true,
    aliases: ["Whammy WH-4", "Whammy IV", "Whammy V"],
  },
  {
    id: "line-6-dl4",
    brand: "Line 6",
    model: "DL4 Delay Modeler",
    type: "delay",
    dims: { widthMm: 305, depthMm: 152, heightMm: 76, source: "maker" },
    power: {
      ma: 2000,
      volts: 9,
      polarity: "center-positive",
      ac: true,
      dcJack: true,
      barrelMm: 2.5,
      source: "maker",
      note: "The famous one. 9V AC, center POSITIVE, 2.5mm barrel, and around 2A. Almost no pedalboard supply can feed it: use its own brick or a supply with a dedicated AC outlet. A normal 9V DC output will not work and can damage it.",
    },
    weightG: 1800,
    aliases: ["DL4"],
  },

  /* --------------------------------------- Off-board: racks and tape echo -- */
  {
    id: "binson-echorec",
    brand: "Binson",
    model: "Echorec",
    type: "delay",
    dims: { widthMm: 430, depthMm: 300, heightMm: 180, source: "estimate" },
    power: { ma: 0, volts: 240, polarity: "center-negative", dcJack: false, source: "maker", note: "Mains powered magnetic drum echo. A tabletop unit." },
    weightG: 12000,
    offBoard: true,
  },
  {
    id: "echoplex-ep-3",
    brand: "Echoplex",
    model: "EP-3",
    type: "delay",
    dims: { widthMm: 356, depthMm: 210, heightMm: 100, source: "estimate" },
    power: { ma: 0, volts: 120, polarity: "center-negative", dcJack: false, source: "maker", note: "Mains powered tape echo. Famous as much for its preamp as its echo." },
    weightG: 5000,
    offBoard: true,
  },
  {
    id: "roland-re-201",
    brand: "Roland",
    model: "RE-201 Space Echo",
    type: "delay",
    dims: { widthMm: 452, depthMm: 275, heightMm: 165, source: "maker" },
    power: { ma: 0, volts: 120, polarity: "center-negative", dcJack: false, source: "maker", note: "Mains powered tape echo and spring reverb. A tabletop unit." },
    weightG: 9500,
    offBoard: true,
  },
  {
    id: "univox-ec-80",
    brand: "Univox",
    model: "EC-80 Echo",
    type: "delay",
    dims: { widthMm: 330, depthMm: 220, heightMm: 120, source: "estimate" },
    power: { ma: 0, volts: 120, polarity: "center-negative", dcJack: false, source: "maker", note: "Mains powered tape echo." },
    weightG: 6000,
    offBoard: true,
  },
  {
    id: "korg-sdd-3000",
    brand: "Korg",
    model: "SDD-3000",
    type: "delay",
    dims: { widthMm: 482, depthMm: 300, heightMm: 88, source: "maker" },
    power: { ma: 0, volts: 120, polarity: "center-negative", dcJack: false, source: "maker", note: "19 inch 2U rack unit. The pedal reissue is a separate entry." },
    weightG: 6000,
    offBoard: true,
  },
  {
    id: "yamaha-spx90",
    brand: "Yamaha",
    model: "SPX90",
    type: "reverb",
    dims: { widthMm: 480, depthMm: 300, heightMm: 44, source: "maker" },
    power: { ma: 0, volts: 120, polarity: "center-negative", dcJack: false, source: "maker", note: "19 inch 1U rack multi-effect." },
    weightG: 4000,
    offBoard: true,
  },

  /* ----------------------------------------------------- Modern boutique -- */
  {
    id: "strymon-el-capistan",
    brand: "Strymon",
    model: "El Capistan",
    type: "delay",
    enclosure: "strymon-compact",
    dims: box("strymon-compact"),
    power: dc(250, "maker"),
    weightG: 570,
  },
  {
    id: "strymon-flint",
    brand: "Strymon",
    model: "Flint",
    type: "reverb",
    enclosure: "strymon-compact",
    dims: box("strymon-compact"),
    power: dc(250, "maker"),
    weightG: 570,
  },
  {
    id: "strymon-bluesky",
    brand: "Strymon",
    model: "blueSky",
    type: "reverb",
    enclosure: "strymon-compact",
    dims: box("strymon-compact"),
    power: dc(250, "maker"),
    weightG: 570,
  },
  {
    id: "strymon-timeline",
    brand: "Strymon",
    model: "TimeLine",
    type: "delay",
    enclosure: "strymon-large",
    dims: box("strymon-large"),
    power: dc(300, "maker"),
    weightG: 1100,
  },
  {
    id: "strymon-bigsky",
    brand: "Strymon",
    model: "BigSky",
    type: "reverb",
    enclosure: "strymon-large",
    dims: box("strymon-large"),
    power: dc(300, "maker"),
    weightG: 1100,
  },
  {
    id: "strymon-mobius",
    brand: "Strymon",
    model: "Mobius",
    type: "modulation",
    enclosure: "strymon-large",
    dims: box("strymon-large"),
    power: dc(300, "maker"),
    weightG: 1100,
  },
  {
    id: "eventide-h9",
    brand: "Eventide",
    model: "H9 Max",
    type: "modulation",
    dims: { widthMm: 100, depthMm: 122, heightMm: 55, source: "maker" },
    power: {
      ma: 500,
      volts: 9,
      polarity: "center-positive",
      dcJack: true,
      source: "maker",
      note: "CENTER POSITIVE, unlike almost everything else on a board, and it wants up to 500mA. Use a reverse polarity cable or an output you can flip. A normal center-negative cable will not power it.",
    },
    weightG: 700,
    aliases: ["H9"],
  },
  {
    /*
     * KORG'S OWN CASTING, and the only sloped-top pedal in this catalogue.
     *
     * No Hammond number to read a size off: the wedge is Korg's, so the figures
     * are marked `estimate` rather than `maker`. They came off a specification
     * written up for this model rather than off Korg's own page, and that is
     * exactly the distinction `SpecSource` exists to record. A layout that
     * places a board on estimated dimensions is a layout that can be a few
     * millimetres out, and the planner says so rather than pretending.
     */
    id: "korg-pitchblack-x",
    brand: "Korg",
    model: "Pitchblack X",
    type: "tuner",
    dims: { widthMm: 69, depthMm: 110, heightMm: 49, source: "estimate" },
    power: dc(50, "estimate"),
    weightG: 320,
  },
  {
    id: "tc-polytune-3",
    brand: "TC Electronic",
    model: "PolyTune 3",
    type: "tuner",
    dims: { widthMm: 72, depthMm: 122, heightMm: 50, source: "maker" },
    power: dc(100, "maker"),
    weightG: 300,
  },
  {
    id: "tc-ditto",
    brand: "TC Electronic",
    model: "Ditto Looper",
    type: "looper",
    dims: { widthMm: 47, depthMm: 93, heightMm: 50, source: "maker" },
    power: dc(100, "maker"),
    weightG: 200,
  },
  {
    /*
     * The mini, which is a different product from the Hall of Fame 2 below and
     * a different enclosure: one knob, and the whole top face is switch. In the
     * same mini pattern the MXR and Ibanez minis use.
     */
    id: "tc-hall-of-fame-mini",
    brand: "TC Electronic",
    model: "Hall of Fame Mini",
    type: "reverb",
    enclosure: "mxr-mini",
    dims: box("mxr-mini"),
    power: dc(100, "maker"),
    weightG: 180,
  },
  {
    id: "tc-hall-of-fame-2",
    brand: "TC Electronic",
    model: "Hall of Fame 2",
    type: "reverb",
    dims: { widthMm: 72, depthMm: 122, heightMm: 50, source: "maker" },
    power: dc(100, "maker"),
    weightG: 300,
  },
  {
    id: "tc-flashback-2",
    brand: "TC Electronic",
    model: "Flashback 2 Delay",
    type: "delay",
    dims: { widthMm: 72, depthMm: 122, heightMm: 50, source: "maker" },
    power: dc(100, "maker"),
    weightG: 300,
  },
  {
    id: "jhs-morning-glory",
    brand: "JHS Pedals",
    model: "Morning Glory V4",
    type: "drive",
    enclosure: "1590B",
    dims: box("1590B"),
    power: dc(20, "maker"),
    weightG: 350,
  },
  {
    id: "jhs-3-series-hall-reverb",
    brand: "JHS Pedals",
    model: "3 Series Hall Reverb",
    type: "reverb",
    enclosure: "1590B",
    dims: box("1590B"),
    power: dc(80),
    weightG: 320,
  },
  {
    id: "walrus-julia",
    brand: "Walrus Audio",
    model: "Julia Chorus/Vibrato",
    type: "modulation",
    enclosure: "1590B",
    dims: box("1590B"),
    power: dc(30, "maker"),
    weightG: 340,
  },
  {
    id: "walrus-slo",
    brand: "Walrus Audio",
    model: "Slö Reverb",
    type: "reverb",
    enclosure: "1590B",
    dims: box("1590B"),
    power: dc(100, "maker"),
    weightG: 340,
    aliases: ["Slo Reverb"],
  },
  {
    id: "wampler-tumnus",
    brand: "Wampler",
    model: "Tumnus",
    type: "drive",
    enclosure: "1590A",
    dims: box("1590A"),
    power: dc(10, "maker"),
    weightG: 200,
  },
  {
    id: "wampler-tumnus-deluxe",
    brand: "Wampler",
    model: "Tumnus Deluxe",
    type: "drive",
    enclosure: "125B",
    dims: box("125B"),
    power: dc(14, "maker"),
    weightG: 400,
  },
  {
    id: "fulltone-ocd",
    brand: "Fulltone",
    model: "OCD",
    type: "drive",
    dims: { widthMm: 66, depthMm: 121, heightMm: 54, source: "maker" },
    power: dc(10, "maker"),
    weightG: 400,
  },
  {
    id: "xotic-ep-booster",
    brand: "Xotic",
    model: "EP Booster",
    type: "drive",
    enclosure: "1590A",
    dims: box("1590A"),
    power: dc(4, "maker"),
    weightG: 180,
  },
  {
    id: "xotic-sp-compressor",
    brand: "Xotic",
    model: "SP Compressor",
    type: "compressor",
    enclosure: "1590A",
    dims: box("1590A"),
    power: dc(6, "maker"),
    weightG: 180,
  },
  {
    id: "keeley-compressor-plus",
    brand: "Keeley",
    model: "Compressor Plus",
    type: "compressor",
    enclosure: "1590B",
    dims: box("1590B"),
    power: dc(10, "maker"),
    weightG: 320,
  },
  {
    id: "earthquaker-dispatch-master",
    brand: "EarthQuaker Devices",
    model: "Dispatch Master",
    type: "delay",
    enclosure: "125B",
    dims: box("125B"),
    power: dc(65, "maker"),
    weightG: 380,
  },
  {
    id: "earthquaker-plumes",
    brand: "EarthQuaker Devices",
    model: "Plumes",
    type: "drive",
    enclosure: "1590B",
    dims: box("1590B"),
    power: dc(10, "maker"),
    weightG: 340,
  },
  {
    id: "chase-bliss-mood",
    brand: "Chase Bliss Audio",
    model: "Mood",
    type: "delay",
    enclosure: "1590B",
    dims: box("1590B"),
    power: dc(300, "maker"),
    weightG: 400,
  },
  {
    id: "origin-cali76-compact",
    brand: "Origin Effects",
    model: "Cali76 Compact",
    type: "compressor",
    enclosure: "125B",
    dims: box("125B"),
    power: dc(120, "maker"),
    weightG: 400,
  },
  {
    id: "source-audio-nemesis",
    brand: "Source Audio",
    model: "Nemesis Delay",
    type: "delay",
    dims: { widthMm: 114, depthMm: 70, heightMm: 55, source: "maker" },
    power: dc(165, "maker"),
    weightG: 400,
  },
  {
    id: "universal-audio-golden",
    brand: "Universal Audio",
    model: "UAFX Golden Reverberator",
    type: "reverb",
    dims: { widthMm: 96, depthMm: 143, heightMm: 60, source: "maker" },
    power: dc(400, "maker"),
    weightG: 700,
  },
]

/** Sorted by brand then model, which is also the order the picker shows. */
export const PEDALS_SORTED: PedalSpec[] = [...PEDALS].sort(
  (a, b) => a.brand.localeCompare(b.brand) || a.model.localeCompare(b.model),
)

const BY_ID = new Map(PEDALS.map((p) => [p.id, p]))

export function pedalById(id: string): PedalSpec | null {
  return BY_ID.get(id) ?? null
}
